# Autogenerated windows.devices.wifidirect.py 2023-09-07 08:59:41.845000
from wrtcommon import *

class WiFiDirectDeviceSelectorType(ENUM):
    """
    enum WiFiDirectDeviceSelectorType
    {
    DeviceInterface     = 0,
    AssociationEndpoint = 1
    };
    """
    DeviceInterface = 0
    AssociationEndpoint = 1
    
class WiFiDirectPairingProcedure(ENUM):
    """
    enum WiFiDirectPairingProcedure
    {
    GroupOwnerNegotiation = 0,
    Invitation            = 1
    };
    """
    GroupOwnerNegotiation = 0
    Invitation = 1
    
class WiFiDirectAdvertisementListenStateDiscoverability(ENUM):
    """
    enum WiFiDirectAdvertisementListenStateDiscoverability
    {
    None      = 0,
    Normal    = 1,
    Intensive = 2
    };
    """
    None_ = 0
    Normal = 1
    Intensive = 2
    
class WiFiDirectConnectionStatus(ENUM):
    """
    enum WiFiDirectConnectionStatus
    {
    Disconnected = 0,
    Connected    = 1
    };
    """
    Disconnected = 0
    Connected = 1
    
class WiFiDirectError(ENUM):
    """
    enum WiFiDirectError
    {
    Success           = 0,
    RadioNotAvailable = 1,
    ResourceInUse     = 2
    };
    """
    Success = 0
    RadioNotAvailable = 1
    ResourceInUse = 2
    
class WiFiDirectAdvertisementPublisherStatus(ENUM):
    """
    enum WiFiDirectAdvertisementPublisherStatus
    {
    Created = 0,
    Started = 1,
    Stopped = 2,
    Aborted = 3
    };
    """
    Created = 0
    Started = 1
    Stopped = 2
    Aborted = 3
    
class WiFiDirectConfigurationMethod(ENUM):
    """
    enum WiFiDirectConfigurationMethod
    {
    ProvidePin = 0,
    DisplayPin = 1,
    PushButton = 2
    };
    """
    ProvidePin = 0
    DisplayPin = 1
    PushButton = 2
    
IID_IWiFiDirectDeviceStatics2 = comtypes.GUID('{1A953E49-B103-437E-9226-AB67971342F9}')
class IWiFiDirectDeviceStatics2(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectDevice)]
    [uuid(1A953E49-B103-437E-9226-AB67971342F9)]
    interface IWiFiDirectDeviceStatics2 : IInspectable
    {
    [overload("GetDeviceSelector")] HRESULT GetDeviceSelector([in] Windows.Devices.WiFiDirect.WiFiDirectDeviceSelectorType type, [out] [retval] HSTRING* result);
    [overload("FromIdAsync")] HRESULT FromIdAsync([in] HSTRING deviceId, [in] Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters* connectionParameters, [out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** result);
    }
    """
    _iid_ = IID_IWiFiDirectDeviceStatics2

IID_IWiFiDirectAdvertisement = comtypes.GUID('{AB511A2D-2A06-49A1-A584-61435C7905A6}')
class IWiFiDirectAdvertisement(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectAdvertisement)]
    [uuid(AB511A2D-2A06-49A1-A584-61435C7905A6)]
    interface IWiFiDirectAdvertisement : IInspectable
    {
    [propget] HRESULT InformationElements([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** value);
    [propput] HRESULT InformationElements([in] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>* value);
    [propget] HRESULT ListenStateDiscoverability([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementListenStateDiscoverability* value);
    [propput] HRESULT ListenStateDiscoverability([in] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementListenStateDiscoverability value);
    [propget] HRESULT IsAutonomousGroupOwnerEnabled([out] [retval] boolean* value);
    [propput] HRESULT IsAutonomousGroupOwnerEnabled([in] boolean value);
    [propget] HRESULT LegacySettings([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectLegacySettings** value);
    }
    """
    _iid_ = IID_IWiFiDirectAdvertisement

IID_IWiFiDirectInformationElementStatics = comtypes.GUID('{DBD02F16-11A5-4E60-8CAA-34772148378A}')
class IWiFiDirectInformationElementStatics(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectInformationElement)]
    [uuid(DBD02F16-11A5-4E60-8CAA-34772148378A)]
    interface IWiFiDirectInformationElementStatics : IInspectable
    {
    HRESULT CreateFromBuffer([in] Windows.Storage.Streams.IBuffer* buffer, [out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** result);
    HRESULT CreateFromDeviceInformation([in] Windows.Devices.Enumeration.DeviceInformation* deviceInformation, [out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** result);
    }
    """
    _iid_ = IID_IWiFiDirectInformationElementStatics

IID_IWiFiDirectAdvertisement2 = comtypes.GUID('{B759AA46-D816-491B-917A-B40D7DC403A2}')
class IWiFiDirectAdvertisement2(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectAdvertisement)]
    [uuid(B759AA46-D816-491B-917A-B40D7DC403A2)]
    interface IWiFiDirectAdvertisement2 : IInspectable
    {
    [propget] HRESULT SupportedConfigurationMethods([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod>** value);
    }
    """
    _iid_ = IID_IWiFiDirectAdvertisement2

IID_IWiFiDirectConnectionRequest = comtypes.GUID('{8EB99605-914F-49C3-A614-D18DC5B19B43}')
class IWiFiDirectConnectionRequest(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionRequest)]
    [uuid(8EB99605-914F-49C3-A614-D18DC5B19B43)]
    interface IWiFiDirectConnectionRequest : IInspectable
    {
    [propget] HRESULT DeviceInformation([out] [retval] Windows.Devices.Enumeration.DeviceInformation** value);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionRequest

IID_IWiFiDirectLegacySettings = comtypes.GUID('{A64FDBBA-F2FD-4567-A91B-F5C2F5321057}')
class IWiFiDirectLegacySettings(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectLegacySettings)]
    [uuid(A64FDBBA-F2FD-4567-A91B-F5C2F5321057)]
    interface IWiFiDirectLegacySettings : IInspectable
    {
    [propget] HRESULT IsEnabled([out] [retval] boolean* value);
    [propput] HRESULT IsEnabled([in] boolean value);
    [propget] HRESULT Ssid([out] [retval] HSTRING* value);
    [propput] HRESULT Ssid([in] HSTRING value);
    [propget] HRESULT Passphrase([out] [retval] Windows.Security.Credentials.PasswordCredential** value);
    [propput] HRESULT Passphrase([in] Windows.Security.Credentials.PasswordCredential* value);
    }
    """
    _iid_ = IID_IWiFiDirectLegacySettings

IID_IAsyncOperation_1_WiFiDirectDevice = comtypes.GUID('{DAD01B61-A82D-566C-BA82-224C11500669}')
class IAsyncOperation_1_WiFiDirectDevice(IInspectable):
    """
    [uuid(DAD01B61-A82D-566C-BA82-224C11500669)]
    interface IAsyncOperation_1_WiFiDirectDevice : IInspectable
    {
    [propput] HRESULT Completed([in] IAsyncOperationCompletedHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*>* handler);
    [propget] HRESULT Completed([out] [retval] IAsyncOperationCompletedHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** handler);
    HRESULT GetResults([out] [retval] Windows.Devices.WiFiDirect.IWiFiDirectDevice** results);
    }
    """
    _iid_ = IID_IAsyncOperation_1_WiFiDirectDevice
    def __init__(self):
        self._OnCompletedFn = None
        self._OnCompletedHandler = None
        self._OnCompletedHandlerClass = None
    
    @property
    def OnCompleted(self):
        logger.info("")
        # type:()->FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherCompletedEventArgs
        return self._OnCompletedFn
    
    @OnCompleted.setter
    def OnCompleted(self, fn):
        logger.info("")
        # type:(FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherCompletedEventArgs) -> None
        if (self._OnCompletedHandler is not None):
            self._OnCompletedHandler = None
            self._OnCompletedHandlerClass = None
            # XXX Does setting a null handler remove it?
            # XXX Does this need to point to the right interface?
            handler = wintypes.POINTER(IAsyncOperationCompletedHandler_1_WiFiDirectDevice)()
    
        if (fn is not None):
            self._OnCompletedHandlerClass = make_typed_event_handler_class(
                IAsyncOperationCompletedHandler_1_WiFiDirectDevice,
                wintypes.POINTER(IAsyncOperation_1_WiFiDirectDevice),
                AsyncStatus,
                fn
            )
            self._OnCompletedHandler = self._OnCompletedHandlerClass()
    
            handler = self._OnCompletedHandler.QueryInterface(self._OnCompletedHandlerClass._event_handler_interface_)
    
        self._IAsyncOperation_1_WiFiDirectDevice__com__set_Completed(handler)
        self._OnCompletedFn = fn
    
class IAsyncOperationCompletedHandler_1_WiFiDirectDevice(comtypes.IUnknown):
    _iid_ = IID_IAsyncOperationCompletedHandler_1_WiFiDirectDevice if ("IID_IAsyncOperationCompletedHandler_1_WiFiDirectDevice" in globals()) else IID_IAsyncEventHandler



IID_IWiFiDirectDevice = comtypes.GUID('{72DEAAA8-72EB-4DAE-8A28-8513355D2777}')
class IWiFiDirectDevice(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectDevice)]
    [uuid(72DEAAA8-72EB-4DAE-8A28-8513355D2777)]
    interface IWiFiDirectDevice : IInspectable
    {
    [propget] HRESULT ConnectionStatus([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectConnectionStatus* value);
    [propget] HRESULT DeviceId([out] [retval] HSTRING* value);
    [eventadd] HRESULT ConnectionStatusChanged([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*, IInspectable*>* handler, [out] [retval] EventRegistrationToken* token);
    [eventremove] HRESULT ConnectionStatusChanged([in] EventRegistrationToken token);
    HRESULT GetConnectionEndpointPairs([out] [retval] Windows.Foundation.Collections.IVectorView<Windows.Networking.EndpointPair*>** value);
    }
    """
    _iid_ = IID_IWiFiDirectDevice
    def __init__(self):
        self._OnConnectionStatusChangedFn = None
        self._OnConnectionStatusChangedToken = None
        self._OnConnectionStatusChangedHandler = None
        self._OnConnectionStatusChangedHandlerClass = None
    
    @property
    def OnConnectionStatusChanged(self):
        logger.info("")
        # type:()->FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherConnectionStatusChangedEventArgs
        return self._OnConnectionStatusChangedFn
    
    @OnConnectionStatusChanged.setter
    def OnConnectionStatusChanged(self, fn):
        logger.info("")
        # type:(FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherConnectionStatusChangedEventArgs) -> None
        if (self._OnConnectionStatusChangedToken is not None):
            self._IWiFiDirectDevice__com_remove_ConnectionStatusChanged(self._OnConnectionStatusChangedToken)
            self._OnConnectionStatusChangedToken = None
            self._OnConnectionStatusChangedHandler = None
            self._OnConnectionStatusChangedHandlerClass = None
    
        if (fn is not None):
            self._OnConnectionStatusChangedHandlerClass = make_typed_event_handler_class(
                TypedEventHandler_2_WiFiDirectDevice_IInspectable,
                wintypes.POINTER(WiFiDirectDevice),
                wintypes.POINTER(IInspectable),
                fn
            )
            self._OnConnectionStatusChangedHandler = self._OnConnectionStatusChangedHandlerClass()
    
            self._OnConnectionStatusChangedToken = EventRegistrationToken()
            handler = self._OnConnectionStatusChangedHandler.QueryInterface(self._OnConnectionStatusChangedHandlerClass._event_handler_interface_)
            self._IWiFiDirectDevice__com_add_ConnectionStatusChanged(
                handler,
                ctypes.byref(self._OnConnectionStatusChangedToken)
            )
        self._OnConnectionStatusChangedFn = fn
    
class TypedEventHandler_2_WiFiDirectDevice_IInspectable(comtypes.IUnknown):
    _iid_ = IID_TypedEventHandler_2_WiFiDirectDevice_IInspectable if ("IID_TypedEventHandler_2_WiFiDirectDevice_IInspectable" in globals()) else IID_ITypedEventHandler



IID_IWiFiDirectInformationElement = comtypes.GUID('{AFFB72D6-76BB-497E-AC8B-DC72838BC309}')
class IWiFiDirectInformationElement(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectInformationElement)]
    [uuid(AFFB72D6-76BB-497E-AC8B-DC72838BC309)]
    interface IWiFiDirectInformationElement : IInspectable
    {
    [propget] HRESULT Oui([out] [retval] Windows.Storage.Streams.IBuffer** value);
    [propput] HRESULT Oui([in] Windows.Storage.Streams.IBuffer* value);
    [propget] HRESULT OuiType([out] [retval] BYTE* value);
    [propput] HRESULT OuiType([in] BYTE value);
    [propget] HRESULT Value([out] [retval] Windows.Storage.Streams.IBuffer** value);
    [propput] HRESULT Value([in] Windows.Storage.Streams.IBuffer* value);
    }
    """
    _iid_ = IID_IWiFiDirectInformationElement

IID_IWiFiDirectConnectionParametersStatics = comtypes.GUID('{598AF493-7642-456F-B9D8-E8A9EB1F401A}')
class IWiFiDirectConnectionParametersStatics(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters)]
    [uuid(598AF493-7642-456F-B9D8-E8A9EB1F401A)]
    interface IWiFiDirectConnectionParametersStatics : IInspectable
    {
    HRESULT GetDevicePairingKinds([in] Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod configurationMethod, [out] [retval] Windows.Devices.Enumeration.DevicePairingKinds* result);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionParametersStatics

IID_IWiFiDirectConnectionParameters = comtypes.GUID('{B2E55405-5702-4B16-A02C-BBCD21EF6098}')
class IWiFiDirectConnectionParameters(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters)]
    [uuid(B2E55405-5702-4B16-A02C-BBCD21EF6098)]
    interface IWiFiDirectConnectionParameters : IInspectable
    {
    [propget] HRESULT GroupOwnerIntent([out] [retval] INT16* value);
    [propput] HRESULT GroupOwnerIntent([in] INT16 value);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionParameters

IID_IWiFiDirectConnectionParameters2 = comtypes.GUID('{AB3B0FBE-AA82-44B4-88C8-E3056B89801D}')
class IWiFiDirectConnectionParameters2(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters)]
    [uuid(AB3B0FBE-AA82-44B4-88C8-E3056B89801D)]
    interface IWiFiDirectConnectionParameters2 : IInspectable
    {
    [propget] HRESULT PreferenceOrderedConfigurationMethods([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod>** value);
    [propget] HRESULT PreferredPairingProcedure([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectPairingProcedure* value);
    [propput] HRESULT PreferredPairingProcedure([in] Windows.Devices.WiFiDirect.WiFiDirectPairingProcedure value);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionParameters2

IID_IWiFiDirectConnectionListener = comtypes.GUID('{699C1B0D-8D13-4EE9-B9EC-9C72F8251F7D}')
class IWiFiDirectConnectionListener(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionListener)]
    [uuid(699C1B0D-8D13-4EE9-B9EC-9C72F8251F7D)]
    interface IWiFiDirectConnectionListener : IInspectable
    {
    [eventadd] HRESULT ConnectionRequested([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectConnectionListener*, Windows.Devices.WiFiDirect.WiFiDirectConnectionRequestedEventArgs*>* handler, [out] [retval] EventRegistrationToken* token);
    [eventremove] HRESULT ConnectionRequested([in] EventRegistrationToken token);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionListener
    def __init__(self):
        self._OnConnectionRequestedFn = None
        self._OnConnectionRequestedToken = None
        self._OnConnectionRequestedHandler = None
        self._OnConnectionRequestedHandlerClass = None
    
    @property
    def OnConnectionRequested(self):
        logger.info("")
        # type:()->FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherConnectionRequestedEventArgs
        return self._OnConnectionRequestedFn
    
    @OnConnectionRequested.setter
    def OnConnectionRequested(self, fn):
        logger.info("")
        # type:(FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherConnectionRequestedEventArgs) -> None
        if (self._OnConnectionRequestedToken is not None):
            self._IWiFiDirectConnectionListener__com_remove_ConnectionRequested(self._OnConnectionRequestedToken)
            self._OnConnectionRequestedToken = None
            self._OnConnectionRequestedHandler = None
            self._OnConnectionRequestedHandlerClass = None
    
        if (fn is not None):
            self._OnConnectionRequestedHandlerClass = make_typed_event_handler_class(
                TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs,
                wintypes.POINTER(WiFiDirectConnectionListener),
                wintypes.POINTER(WiFiDirectConnectionRequestedEventArgs),
                fn
            )
            self._OnConnectionRequestedHandler = self._OnConnectionRequestedHandlerClass()
    
            self._OnConnectionRequestedToken = EventRegistrationToken()
            handler = self._OnConnectionRequestedHandler.QueryInterface(self._OnConnectionRequestedHandlerClass._event_handler_interface_)
            self._IWiFiDirectConnectionListener__com_add_ConnectionRequested(
                handler,
                ctypes.byref(self._OnConnectionRequestedToken)
            )
        self._OnConnectionRequestedFn = fn
    
class TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs(comtypes.IUnknown):
    _iid_ = IID_TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs if ("IID_TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs" in globals()) else IID_ITypedEventHandler



IID_IWiFiDirectConnectionRequestedEventArgs = comtypes.GUID('{F99D20BE-D38D-484F-8215-E7B65ABF244C}')
class IWiFiDirectConnectionRequestedEventArgs(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionRequestedEventArgs)]
    [uuid(F99D20BE-D38D-484F-8215-E7B65ABF244C)]
    interface IWiFiDirectConnectionRequestedEventArgs : IInspectable
    {
    HRESULT GetConnectionRequest([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectConnectionRequest** result);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionRequestedEventArgs

IID_IWiFiDirectAdvertisementPublisherStatusChangedEventArgs = comtypes.GUID('{AAFDE53C-5481-46E6-90DD-32116518F192}')
class IWiFiDirectAdvertisementPublisherStatusChangedEventArgs(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatusChangedEventArgs)]
    [uuid(AAFDE53C-5481-46E6-90DD-32116518F192)]
    interface IWiFiDirectAdvertisementPublisherStatusChangedEventArgs : IInspectable
    {
    [propget] HRESULT Status([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatus* value);
    [propget] HRESULT Error([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectError* value);
    }
    """
    _iid_ = IID_IWiFiDirectAdvertisementPublisherStatusChangedEventArgs

IID_IWiFiDirectAdvertisementPublisher = comtypes.GUID('{B35A2D1A-9B1F-45D9-925A-694D66DF68EF}')
class IWiFiDirectAdvertisementPublisher(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisher)]
    [uuid(B35A2D1A-9B1F-45D9-925A-694D66DF68EF)]
    interface IWiFiDirectAdvertisementPublisher : IInspectable
    {
    [propget] HRESULT Advertisement([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisement** value);
    [propget] HRESULT Status([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatus* value);
    [eventadd] HRESULT StatusChanged([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisher*, Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatusChangedEventArgs*>* handler, [out] [retval] EventRegistrationToken* token);
    [eventremove] HRESULT StatusChanged([in] EventRegistrationToken token);
    HRESULT Start();
    HRESULT Stop();
    }
    """
    _iid_ = IID_IWiFiDirectAdvertisementPublisher
    def __init__(self):
        self._OnStatusChangedFn = None
        self._OnStatusChangedToken = None
        self._OnStatusChangedHandler = None
        self._OnStatusChangedHandlerClass = None
    
    @property
    def OnStatusChanged(self):
        logger.info("")
        # type:()->FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs
        return self._OnStatusChangedFn
    
    @OnStatusChanged.setter
    def OnStatusChanged(self, fn):
        logger.info("")
        # type:(FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs) -> None
        if (self._OnStatusChangedToken is not None):
            self._IWiFiDirectAdvertisementPublisher__com_remove_StatusChanged(self._OnStatusChangedToken)
            self._OnStatusChangedToken = None
            self._OnStatusChangedHandler = None
            self._OnStatusChangedHandlerClass = None
    
        if (fn is not None):
            self._OnStatusChangedHandlerClass = make_typed_event_handler_class(
                TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs,
                wintypes.POINTER(WiFiDirectAdvertisementPublisher),
                wintypes.POINTER(WiFiDirectAdvertisementPublisherStatusChangedEventArgs),
                fn
            )
            self._OnStatusChangedHandler = self._OnStatusChangedHandlerClass()
    
            self._OnStatusChangedToken = EventRegistrationToken()
            handler = self._OnStatusChangedHandler.QueryInterface(self._OnStatusChangedHandlerClass._event_handler_interface_)
            self._IWiFiDirectAdvertisementPublisher__com_add_StatusChanged(
                handler,
                ctypes.byref(self._OnStatusChangedToken)
            )
        self._OnStatusChangedFn = fn
    
class TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs(comtypes.IUnknown):
    _iid_ = IID_TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs if ("IID_TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs" in globals()) else IID_ITypedEventHandler



IID_IWiFiDirectDeviceStatics = comtypes.GUID('{E86CB57C-3AAC-4851-A792-482AAF931B04}')
class IWiFiDirectDeviceStatics(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectDevice)]
    [uuid(E86CB57C-3AAC-4851-A792-482AAF931B04)]
    interface IWiFiDirectDeviceStatics : IInspectable
    {
    [overload("GetDeviceSelector")] HRESULT GetDeviceSelector([out] [retval] HSTRING* deviceSelector);
    [overload("FromIdAsync")] HRESULT FromIdAsync([in] HSTRING deviceId, [out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** asyncOp);
    }
    """
    _iid_ = IID_IWiFiDirectDeviceStatics

class WiFiDirectDevice(IWiFiDirectDevice):
    """
    [static(Windows.Devices.WiFiDirect.IWiFiDirectDeviceStatics, Windows.Foundation.UniversalApiContract, 1.0)]
    [static(Windows.Devices.WiFiDirect.IWiFiDirectDeviceStatics2, Windows.Foundation.UniversalApiContract, 1.0)]
    runtimeclass WiFiDirectDevice
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectDevice;
    }
    """

class IWiFiDirectDeviceStatics_s(IInspectable):
    _iid_ = IID_IWiFiDirectDeviceStatics
    def __new__(cls):
        static = activate_static("Windows.Devices.WiFiDirect.WiFiDirectDevice", IWiFiDirectDeviceStatics)
        return static
    
class IWiFiDirectDeviceStatics2_s(IInspectable):
    _iid_ = IID_IWiFiDirectDeviceStatics2
    def __new__(cls):
        static = activate_static("Windows.Devices.WiFiDirect.WiFiDirectDevice", IWiFiDirectDeviceStatics2)
        return static
    
class WiFiDirectConnectionRequest(IWiFiDirectConnectionRequest):
    """
    runtimeclass WiFiDirectConnectionRequest
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectConnectionRequest;
    }
    """

class WiFiDirectInformationElement(IWiFiDirectInformationElement):
    """
    [activatable(Windows.Foundation.UniversalApiContract, 1.0)]
    [static(Windows.Devices.WiFiDirect.IWiFiDirectInformationElementStatics, Windows.Foundation.UniversalApiContract, 1.0)]
    runtimeclass WiFiDirectInformationElement
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectInformationElement;
    }
    """
    def __new__(cls):
        instance = activate_instance('Windows.Devices.WiFiDirect.WiFiDirectInformationElement', IWiFiDirectInformationElement)
        # XXX This calls __init__ to wrap the object just created so the
        #     pythonic methods in the wrapper can be used (eg event
        #     hooking), do it in activate_instance or find another
        #     mechanism?
        instance.__init__()
        return instance
    

class IWiFiDirectInformationElementStatics_s(IInspectable):
    _iid_ = IID_IWiFiDirectInformationElementStatics
    def __new__(cls):
        static = activate_static("Windows.Devices.WiFiDirect.WiFiDirectInformationElement", IWiFiDirectInformationElementStatics)
        return static
    
class WiFiDirectConnectionParameters(IWiFiDirectConnectionParameters):
    """
    [activatable(Windows.Foundation.UniversalApiContract, 1.0)]
    [static(Windows.Devices.WiFiDirect.IWiFiDirectConnectionParametersStatics, Windows.Foundation.UniversalApiContract, 2.0)]
    runtimeclass WiFiDirectConnectionParameters
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectConnectionParameters;
    }
    """
    def __new__(cls):
        instance = activate_instance('Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters', IWiFiDirectConnectionParameters)
        # XXX This calls __init__ to wrap the object just created so the
        #     pythonic methods in the wrapper can be used (eg event
        #     hooking), do it in activate_instance or find another
        #     mechanism?
        instance.__init__()
        return instance
    

class IWiFiDirectConnectionParametersStatics_s(IInspectable):
    _iid_ = IID_IWiFiDirectConnectionParametersStatics
    def __new__(cls):
        static = activate_static("Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters", IWiFiDirectConnectionParametersStatics)
        return static
    
class WiFiDirectConnectionRequestedEventArgs(IWiFiDirectConnectionRequestedEventArgs):
    """
    runtimeclass WiFiDirectConnectionRequestedEventArgs
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectConnectionRequestedEventArgs;
    }
    """

class WiFiDirectConnectionListener(IWiFiDirectConnectionListener):
    """
    [activatable(Windows.Foundation.UniversalApiContract, 1.0)]
    runtimeclass WiFiDirectConnectionListener
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectConnectionListener;
    }
    """
    def __new__(cls):
        instance = activate_instance('Windows.Devices.WiFiDirect.WiFiDirectConnectionListener', IWiFiDirectConnectionListener)
        # XXX This calls __init__ to wrap the object just created so the
        #     pythonic methods in the wrapper can be used (eg event
        #     hooking), do it in activate_instance or find another
        #     mechanism?
        instance.__init__()
        return instance
    

class WiFiDirectAdvertisementPublisherStatusChangedEventArgs(IWiFiDirectAdvertisementPublisherStatusChangedEventArgs):
    """
    runtimeclass WiFiDirectAdvertisementPublisherStatusChangedEventArgs
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectAdvertisementPublisherStatusChangedEventArgs;
    }
    """

class WiFiDirectAdvertisementPublisher(IWiFiDirectAdvertisementPublisher):
    """
    [activatable(Windows.Foundation.UniversalApiContract, 1.0)]
    runtimeclass WiFiDirectAdvertisementPublisher
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectAdvertisementPublisher;
    }
    """
    def __new__(cls):
        instance = activate_instance('Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisher', IWiFiDirectAdvertisementPublisher)
        # XXX This calls __init__ to wrap the object just created so the
        #     pythonic methods in the wrapper can be used (eg event
        #     hooking), do it in activate_instance or find another
        #     mechanism?
        instance.__init__()
        return instance
    

class WiFiDirectLegacySettings(IWiFiDirectLegacySettings):
    """
    runtimeclass WiFiDirectLegacySettings
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectLegacySettings;
    }
    """

class WiFiDirectAdvertisement(IWiFiDirectAdvertisement):
    """
    runtimeclass WiFiDirectAdvertisement
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectAdvertisement;
    }
    """

IWiFiDirectDeviceStatics2._methods_ = [
    # [overload("GetDeviceSelector")] HRESULT GetDeviceSelector([in] Windows.Devices.WiFiDirect.WiFiDirectDeviceSelectorType type,[out] [retval] HSTRING* result)
    comtypes.COMMETHOD(
        ['overload("GetDeviceSelector")'], wintypes.HRESULT, 'GetDeviceSelector',
        (['in'], WiFiDirectDeviceSelectorType, 'type'),
        (['out','retval'], wintypes.POINTER(HSTRING), 'result'),
    ),
    # [overload("FromIdAsync")] HRESULT FromIdAsync([in] HSTRING deviceId,[in] Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters* connectionParameters,[out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** result)
    comtypes.COMMETHOD(
        ['overload("FromIdAsync")'], wintypes.HRESULT, 'FromIdAsync',
        (['in'], HSTRING, 'deviceId'),
        (['in'], wintypes.POINTER(WiFiDirectConnectionParameters), 'connectionParameters'),
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IAsyncOperation_1_WiFiDirectDevice)), 'result'),
    ),
]


IWiFiDirectAdvertisement._methods_ = [
    # [propget] HRESULT InformationElements([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'InformationElements',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectInformationElement)), 'value'),
    ),
    # [propput] HRESULT InformationElements([in] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>* value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'InformationElements',
        (['in'], wintypes.POINTER(IVector_1_WiFiDirectInformationElement), 'value'),
    ),
    # [propget] HRESULT ListenStateDiscoverability([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementListenStateDiscoverability* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'ListenStateDiscoverability',
        (['out','retval'], wintypes.POINTER(WiFiDirectAdvertisementListenStateDiscoverability), 'value'),
    ),
    # [propput] HRESULT ListenStateDiscoverability([in] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementListenStateDiscoverability value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'ListenStateDiscoverability',
        (['in'], WiFiDirectAdvertisementListenStateDiscoverability, 'value'),
    ),
    # [propget] HRESULT IsAutonomousGroupOwnerEnabled([out] [retval] boolean* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'IsAutonomousGroupOwnerEnabled',
        (['out','retval'], wintypes.POINTER(wintypes.BOOL), 'value'),
    ),
    # [propput] HRESULT IsAutonomousGroupOwnerEnabled([in] boolean value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'IsAutonomousGroupOwnerEnabled',
        (['in'], wintypes.BOOL, 'value'),
    ),
    # [propget] HRESULT LegacySettings([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectLegacySettings** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'LegacySettings',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(WiFiDirectLegacySettings)), 'value'),
    ),
]


IWiFiDirectInformationElementStatics._methods_ = [
    # [None] HRESULT CreateFromBuffer([in] Windows.Storage.Streams.IBuffer* buffer,[out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** result)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'CreateFromBuffer',
        (['in'], wintypes.POINTER(IBuffer), 'buffer'),
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectInformationElement)), 'result'),
    ),
    # [None] HRESULT CreateFromDeviceInformation([in] Windows.Devices.Enumeration.DeviceInformation* deviceInformation,[out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** result)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'CreateFromDeviceInformation',
        (['in'], wintypes.POINTER(DeviceInformation), 'deviceInformation'),
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectInformationElement)), 'result'),
    ),
]


IWiFiDirectAdvertisement2._methods_ = [
    # [propget] HRESULT SupportedConfigurationMethods([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod>** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'SupportedConfigurationMethods',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectConfigurationMethod)), 'value'),
    ),
]


IWiFiDirectConnectionRequest._methods_ = [
    # [propget] HRESULT DeviceInformation([out] [retval] Windows.Devices.Enumeration.DeviceInformation** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'DeviceInformation',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(DeviceInformation)), 'value'),
    ),
]


IWiFiDirectLegacySettings._methods_ = [
    # [propget] HRESULT IsEnabled([out] [retval] boolean* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'IsEnabled',
        (['out','retval'], wintypes.POINTER(wintypes.BOOL), 'value'),
    ),
    # [propput] HRESULT IsEnabled([in] boolean value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'IsEnabled',
        (['in'], wintypes.BOOL, 'value'),
    ),
    # [propget] HRESULT Ssid([out] [retval] HSTRING* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Ssid',
        (['out','retval'], wintypes.POINTER(HSTRING), 'value'),
    ),
    # [propput] HRESULT Ssid([in] HSTRING value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Ssid',
        (['in'], HSTRING, 'value'),
    ),
    # [propget] HRESULT Passphrase([out] [retval] Windows.Security.Credentials.PasswordCredential** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Passphrase',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(PasswordCredential)), 'value'),
    ),
    # [propput] HRESULT Passphrase([in] Windows.Security.Credentials.PasswordCredential* value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Passphrase',
        (['in'], wintypes.POINTER(PasswordCredential), 'value'),
    ),
]


IAsyncOperation_1_WiFiDirectDevice._methods_ = [
    # [propput] HRESULT Completed([in] IAsyncOperationCompletedHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*>* handler)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Completed',
        (['in'], wintypes.POINTER(IAsyncOperationCompletedHandler_1_WiFiDirectDevice), 'handler'),
    ),
    # [propget] HRESULT Completed([out] [retval] IAsyncOperationCompletedHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** handler)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Completed',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IAsyncOperationCompletedHandler_1_WiFiDirectDevice)), 'handler'),
    ),
    # [None] HRESULT GetResults([out] [retval] Windows.Devices.WiFiDirect.IWiFiDirectDevice** results)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetResults',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IWiFiDirectDevice)), 'results'),
    ),
]

IAsyncOperationCompletedHandler_1_WiFiDirectDevice._methods_ = [
    # HRESULT Invoke([in] IAsyncOperation_1_WiFiDirectDevice *sender, [in] AsyncStatus *args)
    comtypes.COMMETHOD(
        [''], wintypes.HRESULT, "Invoke",
        (['in'], wintypes.POINTER(IAsyncOperation_1_WiFiDirectDevice)),
        (['in'], AsyncStatus),
    ),
]


IWiFiDirectDevice._methods_ = [
    # [propget] HRESULT ConnectionStatus([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectConnectionStatus* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'ConnectionStatus',
        (['out','retval'], wintypes.POINTER(WiFiDirectConnectionStatus), 'value'),
    ),
    # [propget] HRESULT DeviceId([out] [retval] HSTRING* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'DeviceId',
        (['out','retval'], wintypes.POINTER(HSTRING), 'value'),
    ),
    # [eventadd] HRESULT ConnectionStatusChanged([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*,IInspectable*>* handler,[out] [retval] EventRegistrationToken* token)
    comtypes.COMMETHOD(
        ['eventadd'], wintypes.HRESULT, 'add_ConnectionStatusChanged',
        (['in'], wintypes.POINTER(TypedEventHandler_2_WiFiDirectDevice_IInspectable), 'handler'),
        (['out','retval'], wintypes.POINTER(EventRegistrationToken), 'token'),
    ),
    # [eventremove] HRESULT ConnectionStatusChanged([in] EventRegistrationToken token)
    comtypes.COMMETHOD(
        ['eventremove'], wintypes.HRESULT, 'remove_ConnectionStatusChanged',
        (['in'], EventRegistrationToken, 'token'),
    ),
    # [None] HRESULT GetConnectionEndpointPairs([out] [retval] Windows.Foundation.Collections.IVectorView<Windows.Networking.EndpointPair*>** value)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetConnectionEndpointPairs',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVectorView_1_EndpointPair)), 'value'),
    ),
]

TypedEventHandler_2_WiFiDirectDevice_IInspectable._methods_ = [
    # HRESULT Invoke([in] WiFiDirectDevice *sender, [in] wintypes.POINTER(IInspectable) *args)
    comtypes.COMMETHOD(
        [''], wintypes.HRESULT, "Invoke",
        (['in'], wintypes.POINTER(WiFiDirectDevice)),
        (['in'], wintypes.POINTER(IInspectable)),
    ),
]


IWiFiDirectInformationElement._methods_ = [
    # [propget] HRESULT Oui([out] [retval] Windows.Storage.Streams.IBuffer** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Oui',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IBuffer)), 'value'),
    ),
    # [propput] HRESULT Oui([in] Windows.Storage.Streams.IBuffer* value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Oui',
        (['in'], wintypes.POINTER(IBuffer), 'value'),
    ),
    # [propget] HRESULT OuiType([out] [retval] BYTE* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'OuiType',
        (['out','retval'], wintypes.POINTER(wintypes.BYTE), 'value'),
    ),
    # [propput] HRESULT OuiType([in] BYTE value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'OuiType',
        (['in'], wintypes.BYTE, 'value'),
    ),
    # [propget] HRESULT Value([out] [retval] Windows.Storage.Streams.IBuffer** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Value',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IBuffer)), 'value'),
    ),
    # [propput] HRESULT Value([in] Windows.Storage.Streams.IBuffer* value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Value',
        (['in'], wintypes.POINTER(IBuffer), 'value'),
    ),
]


IWiFiDirectConnectionParametersStatics._methods_ = [
    # [None] HRESULT GetDevicePairingKinds([in] Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod configurationMethod,[out] [retval] Windows.Devices.Enumeration.DevicePairingKinds* result)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetDevicePairingKinds',
        (['in'], WiFiDirectConfigurationMethod, 'configurationMethod'),
        (['out','retval'], wintypes.POINTER(DevicePairingKinds), 'result'),
    ),
]


IWiFiDirectConnectionParameters._methods_ = [
    # [propget] HRESULT GroupOwnerIntent([out] [retval] INT16* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'GroupOwnerIntent',
        (['out','retval'], wintypes.POINTER(wintypes.SHORT), 'value'),
    ),
    # [propput] HRESULT GroupOwnerIntent([in] INT16 value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'GroupOwnerIntent',
        (['in'], wintypes.SHORT, 'value'),
    ),
]


IWiFiDirectConnectionParameters2._methods_ = [
    # [propget] HRESULT PreferenceOrderedConfigurationMethods([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod>** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'PreferenceOrderedConfigurationMethods',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectConfigurationMethod)), 'value'),
    ),
    # [propget] HRESULT PreferredPairingProcedure([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectPairingProcedure* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'PreferredPairingProcedure',
        (['out','retval'], wintypes.POINTER(WiFiDirectPairingProcedure), 'value'),
    ),
    # [propput] HRESULT PreferredPairingProcedure([in] Windows.Devices.WiFiDirect.WiFiDirectPairingProcedure value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'PreferredPairingProcedure',
        (['in'], WiFiDirectPairingProcedure, 'value'),
    ),
]


IWiFiDirectConnectionListener._methods_ = [
    # [eventadd] HRESULT ConnectionRequested([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectConnectionListener*,Windows.Devices.WiFiDirect.WiFiDirectConnectionRequestedEventArgs*>* handler,[out] [retval] EventRegistrationToken* token)
    comtypes.COMMETHOD(
        ['eventadd'], wintypes.HRESULT, 'add_ConnectionRequested',
        (['in'], wintypes.POINTER(TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs), 'handler'),
        (['out','retval'], wintypes.POINTER(EventRegistrationToken), 'token'),
    ),
    # [eventremove] HRESULT ConnectionRequested([in] EventRegistrationToken token)
    comtypes.COMMETHOD(
        ['eventremove'], wintypes.HRESULT, 'remove_ConnectionRequested',
        (['in'], EventRegistrationToken, 'token'),
    ),
]

TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs._methods_ = [
    # HRESULT Invoke([in] WiFiDirectConnectionListener *sender, [in] wintypes.POINTER(WiFiDirectConnectionRequestedEventArgs) *args)
    comtypes.COMMETHOD(
        [''], wintypes.HRESULT, "Invoke",
        (['in'], wintypes.POINTER(WiFiDirectConnectionListener)),
        (['in'], wintypes.POINTER(WiFiDirectConnectionRequestedEventArgs)),
    ),
]


IWiFiDirectConnectionRequestedEventArgs._methods_ = [
    # [None] HRESULT GetConnectionRequest([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectConnectionRequest** result)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetConnectionRequest',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(WiFiDirectConnectionRequest)), 'result'),
    ),
]


IWiFiDirectAdvertisementPublisherStatusChangedEventArgs._methods_ = [
    # [propget] HRESULT Status([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatus* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Status',
        (['out','retval'], wintypes.POINTER(WiFiDirectAdvertisementPublisherStatus), 'value'),
    ),
    # [propget] HRESULT Error([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectError* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Error',
        (['out','retval'], wintypes.POINTER(WiFiDirectError), 'value'),
    ),
]


IWiFiDirectAdvertisementPublisher._methods_ = [
    # [propget] HRESULT Advertisement([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisement** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Advertisement',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(WiFiDirectAdvertisement)), 'value'),
    ),
    # [propget] HRESULT Status([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatus* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Status',
        (['out','retval'], wintypes.POINTER(WiFiDirectAdvertisementPublisherStatus), 'value'),
    ),
    # [eventadd] HRESULT StatusChanged([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisher*,Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatusChangedEventArgs*>* handler,[out] [retval] EventRegistrationToken* token)
    comtypes.COMMETHOD(
        ['eventadd'], wintypes.HRESULT, 'add_StatusChanged',
        (['in'], wintypes.POINTER(TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs), 'handler'),
        (['out','retval'], wintypes.POINTER(EventRegistrationToken), 'token'),
    ),
    # [eventremove] HRESULT StatusChanged([in] EventRegistrationToken token)
    comtypes.COMMETHOD(
        ['eventremove'], wintypes.HRESULT, 'remove_StatusChanged',
        (['in'], EventRegistrationToken, 'token'),
    ),
    # [None] HRESULT Start()
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Start',
    ),
    # [None] HRESULT Stop()
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Stop',
    ),
]

TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs._methods_ = [
    # HRESULT Invoke([in] WiFiDirectAdvertisementPublisher *sender, [in] wintypes.POINTER(WiFiDirectAdvertisementPublisherStatusChangedEventArgs) *args)
    comtypes.COMMETHOD(
        [''], wintypes.HRESULT, "Invoke",
        (['in'], wintypes.POINTER(WiFiDirectAdvertisementPublisher)),
        (['in'], wintypes.POINTER(WiFiDirectAdvertisementPublisherStatusChangedEventArgs)),
    ),
]


IWiFiDirectDeviceStatics._methods_ = [
    # [overload("GetDeviceSelector")] HRESULT GetDeviceSelector([out] [retval] HSTRING* deviceSelector)
    comtypes.COMMETHOD(
        ['overload("GetDeviceSelector")'], wintypes.HRESULT, 'GetDeviceSelector',
        (['out','retval'], wintypes.POINTER(HSTRING), 'deviceSelector'),
    ),
    # [overload("FromIdAsync")] HRESULT FromIdAsync([in] HSTRING deviceId,[out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** asyncOp)
    comtypes.COMMETHOD(
        ['overload("FromIdAsync")'], wintypes.HRESULT, 'FromIdAsync',
        (['in'], HSTRING, 'deviceId'),
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IAsyncOperation_1_WiFiDirectDevice)), 'asyncOp'),
    ),
]


