# Autogenerated from windows.devices.wifidirect.idl, wifidirect.hacks.idl on 2023-09-13 12:54:59.782000
from wrtcommon import *

class WiFiDirectDeviceSelectorType(ENUM):
    """
    enum WiFiDirectDeviceSelectorType
    {
    DeviceInterface     = 0,
    AssociationEndpoint = 1
    };
    """
    DeviceInterface = 0
    AssociationEndpoint = 1
    
class WiFiDirectAdvertisementListenStateDiscoverability(ENUM):
    """
    enum WiFiDirectAdvertisementListenStateDiscoverability
    {
    None      = 0,
    Normal    = 1,
    Intensive = 2
    };
    """
    None_ = 0
    Normal = 1
    Intensive = 2
    
class WiFiDirectConnectionStatus(ENUM):
    """
    enum WiFiDirectConnectionStatus
    {
    Disconnected = 0,
    Connected    = 1
    };
    """
    Disconnected = 0
    Connected = 1
    
class WiFiDirectError(ENUM):
    """
    enum WiFiDirectError
    {
    Success           = 0,
    RadioNotAvailable = 1,
    ResourceInUse     = 2
    };
    """
    Success = 0
    RadioNotAvailable = 1
    ResourceInUse = 2
    
class WiFiDirectAdvertisementPublisherStatus(ENUM):
    """
    enum WiFiDirectAdvertisementPublisherStatus
    {
    Created = 0,
    Started = 1,
    Stopped = 2,
    Aborted = 3
    };
    """
    Created = 0
    Started = 1
    Stopped = 2
    Aborted = 3
    
class DevicePairingKinds(ENUM):
    """
    enum DevicePairingKinds
    {
    None            = 0x0,
    ConfirmOnly     = 0x1,
    DisplayPin      = 0x2,
    ProvidePin      = 0x4,
    ConfirmPinMatch = 0x8
    };
    """
    None_ = 0
    ConfirmOnly = 1
    DisplayPin = 2
    ProvidePin = 4
    ConfirmPinMatch = 8
    
class WiFiDirectConfigurationMethod(ENUM):
    """
    enum WiFiDirectConfigurationMethod
    {
    ProvidePin = 0,
    DisplayPin = 1,
    PushButton = 2
    };
    """
    ProvidePin = 0
    DisplayPin = 1
    PushButton = 2
    
class WiFiDirectPairingProcedure(ENUM):
    """
    enum WiFiDirectPairingProcedure
    {
    GroupOwnerNegotiation = 0,
    Invitation            = 1
    };
    """
    GroupOwnerNegotiation = 0
    Invitation = 1
    
IID_EnclosureLocation = comtypes.GUID('{42340A27-5810-459C-AABB-C65E1F813ECF}')
class EnclosureLocation(IInspectable):
    """
    [uuid(42340A27-5810-459C-AABB-C65E1F813ECF)]
    interface EnclosureLocation : IInspectable
    {
    }
    """
    _iid_ = IID_EnclosureLocation

IID_IWiFiDirectDeviceStatics2 = comtypes.GUID('{1A953E49-B103-437E-9226-AB67971342F9}')
class IWiFiDirectDeviceStatics2(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectDevice)]
    [uuid(1A953E49-B103-437E-9226-AB67971342F9)]
    interface IWiFiDirectDeviceStatics2 : IInspectable
    {
    [overload("GetDeviceSelector")] HRESULT GetDeviceSelector([in] Windows.Devices.WiFiDirect.WiFiDirectDeviceSelectorType type, [out] [retval] HSTRING* result);
    [overload("FromIdAsync")] HRESULT FromIdAsync([in] HSTRING deviceId, [in] Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters* connectionParameters, [out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** result);
    }
    """
    _iid_ = IID_IWiFiDirectDeviceStatics2

IID_IWiFiDirectAdvertisement = comtypes.GUID('{AB511A2D-2A06-49A1-A584-61435C7905A6}')
class IWiFiDirectAdvertisement(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectAdvertisement)]
    [uuid(AB511A2D-2A06-49A1-A584-61435C7905A6)]
    interface IWiFiDirectAdvertisement : IInspectable
    {
    [propget] HRESULT InformationElements([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** value);
    [propput] HRESULT InformationElements([in] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>* value);
    [propget] HRESULT ListenStateDiscoverability([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementListenStateDiscoverability* value);
    [propput] HRESULT ListenStateDiscoverability([in] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementListenStateDiscoverability value);
    [propget] HRESULT IsAutonomousGroupOwnerEnabled([out] [retval] boolean* value);
    [propput] HRESULT IsAutonomousGroupOwnerEnabled([in] boolean value);
    [propget] HRESULT LegacySettings([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectLegacySettings** value);
    }
    """
    _iid_ = IID_IWiFiDirectAdvertisement

IID_IWiFiDirectAdvertisementPublisher = comtypes.GUID('{B35A2D1A-9B1F-45D9-925A-694D66DF68EF}')
class IWiFiDirectAdvertisementPublisher(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisher)]
    [uuid(B35A2D1A-9B1F-45D9-925A-694D66DF68EF)]
    interface IWiFiDirectAdvertisementPublisher : IInspectable
    {
    [propget] HRESULT Advertisement([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisement** value);
    [propget] HRESULT Status([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatus* value);
    [eventadd] HRESULT StatusChanged([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisher*, Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatusChangedEventArgs*>* handler, [out] [retval] EventRegistrationToken* token);
    [eventremove] HRESULT StatusChanged([in] EventRegistrationToken token);
    HRESULT Start();
    HRESULT Stop();
    }
    """
    _iid_ = IID_IWiFiDirectAdvertisementPublisher
    def __init__(self):
        self._OnStatusChangedFn = None
        self._OnStatusChangedToken = None
        self._OnStatusChangedHandler = None
        self._OnStatusChangedHandlerClass = None
    
    @property
    def OnStatusChanged(self):
        logger.info("")
        # type:()->FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs
        return self._OnStatusChangedFn
    
    @OnStatusChanged.setter
    def OnStatusChanged(self, fn):
        logger.info("")
        # type:(FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs) -> None
        if (self._OnStatusChangedToken is not None):
            self._IWiFiDirectAdvertisementPublisher__com_remove_StatusChanged(self._OnStatusChangedToken)
            self._OnStatusChangedToken = None
            self._OnStatusChangedHandler = None
            self._OnStatusChangedHandlerClass = None
    
        if (fn is not None):
            self._OnStatusChangedHandlerClass = make_typed_event_handler_class(
                TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs,
                wintypes.POINTER(WiFiDirectAdvertisementPublisher),
                wintypes.POINTER(WiFiDirectAdvertisementPublisherStatusChangedEventArgs),
                fn
            )
            self._OnStatusChangedHandler = self._OnStatusChangedHandlerClass()
    
            self._OnStatusChangedToken = EventRegistrationToken()
            handler = self._OnStatusChangedHandler.QueryInterface(self._OnStatusChangedHandlerClass._event_handler_interface_)
            self._IWiFiDirectAdvertisementPublisher__com_add_StatusChanged(
                handler,
                ctypes.byref(self._OnStatusChangedToken)
            )
        self._OnStatusChangedFn = fn
    

IID_IWiFiDirectInformationElementStatics = comtypes.GUID('{DBD02F16-11A5-4E60-8CAA-34772148378A}')
class IWiFiDirectInformationElementStatics(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectInformationElement)]
    [uuid(DBD02F16-11A5-4E60-8CAA-34772148378A)]
    interface IWiFiDirectInformationElementStatics : IInspectable
    {
    HRESULT CreateFromBuffer([in] Windows.Storage.Streams.IBuffer* buffer, [out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** result);
    HRESULT CreateFromDeviceInformation([in] Windows.Devices.Enumeration.DeviceInformation* deviceInformation, [out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** result);
    }
    """
    _iid_ = IID_IWiFiDirectInformationElementStatics

IID_IWiFiDirectAdvertisement2 = comtypes.GUID('{B759AA46-D816-491B-917A-B40D7DC403A2}')
class IWiFiDirectAdvertisement2(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectAdvertisement)]
    [uuid(B759AA46-D816-491B-917A-B40D7DC403A2)]
    interface IWiFiDirectAdvertisement2 : IInspectable
    {
    [propget] HRESULT SupportedConfigurationMethods([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod>** value);
    }
    """
    _iid_ = IID_IWiFiDirectAdvertisement2

IID_IWiFiDirectConnectionRequest = comtypes.GUID('{8EB99605-914F-49C3-A614-D18DC5B19B43}')
class IWiFiDirectConnectionRequest(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionRequest)]
    [uuid(8EB99605-914F-49C3-A614-D18DC5B19B43)]
    interface IWiFiDirectConnectionRequest : IInspectable
    {
    [propget] HRESULT DeviceInformation([out] [retval] Windows.Devices.Enumeration.DeviceInformation** value);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionRequest

IID_IVector_1_WiFiDirectConfigurationMethod = comtypes.GUID('{913337e9-11a1-4345-a3a2-4e7f956e222d}')
class IVector_1_WiFiDirectConfigurationMethod(IInspectable):
    """
    uuid(913337e9-11a1-4345-a3a2-4e7f956e222d)
    interface IVector_1_WiFiDirectConfigurationMethod : IInspectable
    {
    }
    """
    _iid_ = IID_IVector_1_WiFiDirectConfigurationMethod

IID_IWiFiDirectLegacySettings = comtypes.GUID('{A64FDBBA-F2FD-4567-A91B-F5C2F5321057}')
class IWiFiDirectLegacySettings(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectLegacySettings)]
    [uuid(A64FDBBA-F2FD-4567-A91B-F5C2F5321057)]
    interface IWiFiDirectLegacySettings : IInspectable
    {
    [propget] HRESULT IsEnabled([out] [retval] boolean* value);
    [propput] HRESULT IsEnabled([in] boolean value);
    [propget] HRESULT Ssid([out] [retval] HSTRING* value);
    [propput] HRESULT Ssid([in] HSTRING value);
    [propget] HRESULT Passphrase([out] [retval] Windows.Security.Credentials.PasswordCredential** value);
    [propput] HRESULT Passphrase([in] Windows.Security.Credentials.PasswordCredential* value);
    }
    """
    _iid_ = IID_IWiFiDirectLegacySettings

IID_DeviceInformationUpdate = comtypes.GUID('{8F315305-D972-44B7-A37E-9E822C78213B}')
class DeviceInformationUpdate(IInspectable):
    """
    [exclusiveto(Windows.Devices.Enumeration.DeviceInformationUpdate)]
    [uuid(8F315305-D972-44B7-A37E-9E822C78213B)]
    interface DeviceInformationUpdate : IInspectable
    {
    }
    """
    _iid_ = IID_DeviceInformationUpdate

IID_IPropertySet = comtypes.GUID('{8A43ED9F-F4E6-4421-ACF9-1DAB2986820C}')
class IPropertySet(IInspectable):
    """
    [uuid(8A43ED9F-F4E6-4421-ACF9-1DAB2986820C)]
    interface IPropertySet : IInspectable
    {
    }
    """
    _iid_ = IID_IPropertySet

IID_IBuffer = comtypes.GUID('{905A0FE0-BC53-11DF-8C49-001E4FC686DA}')
class IBuffer(IInspectable):
    """
    [uuid(905A0FE0-BC53-11DF-8C49-001E4FC686DA)]
    interface IBuffer : IInspectable
    {
    [propget] HRESULT Capacity([out] [retval] UINT32* value);
    [propget] HRESULT Length([out] [retval] UINT32* value);
    [propput] HRESULT Length([in] UINT32 value);
    }
    """
    _iid_ = IID_IBuffer

IID_IAsyncOperation_1_WiFiDirectDevice = comtypes.GUID('{DAD01B61-A82D-566C-BA82-224C11500669}')
class IAsyncOperation_1_WiFiDirectDevice(IInspectable):
    """
    [uuid(DAD01B61-A82D-566C-BA82-224C11500669)]
    interface IAsyncOperation_1_WiFiDirectDevice : IInspectable
    {
    [propput] HRESULT Completed([in] IAsyncOperationCompletedHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*>* handler);
    [propget] HRESULT Completed([out] [retval] IAsyncOperationCompletedHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** handler);
    HRESULT GetResults([out] [retval] Windows.Devices.WiFiDirect.IWiFiDirectDevice** results);
    }
    """
    _iid_ = IID_IAsyncOperation_1_WiFiDirectDevice
    def __init__(self):
        self._OnCompletedFn = None
        self._OnCompletedHandler = None
        self._OnCompletedHandlerClass = None
    
    @property
    def OnCompleted(self):
        logger.info("")
        # type:()->FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherCompletedEventArgs
        return self._OnCompletedFn
    
    @OnCompleted.setter
    def OnCompleted(self, fn):
        logger.info("")
        # type:(FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherCompletedEventArgs) -> None
        if (self._OnCompletedHandler is not None):
            self._OnCompletedHandler = None
            self._OnCompletedHandlerClass = None
            # XXX Does setting a null handler remove it?
            # XXX Does this need to point to the right interface?
            handler = wintypes.POINTER(IAsyncOperationCompletedHandler_1_WiFiDirectDevice)()
    
        if (fn is not None):
            self._OnCompletedHandlerClass = make_typed_event_handler_class(
                IAsyncOperationCompletedHandler_1_WiFiDirectDevice,
                wintypes.POINTER(IAsyncOperation_1_WiFiDirectDevice),
                AsyncStatus,
                fn
            )
            self._OnCompletedHandler = self._OnCompletedHandlerClass()
    
            handler = self._OnCompletedHandler.QueryInterface(self._OnCompletedHandlerClass._event_handler_interface_)
    
        self._IAsyncOperation_1_WiFiDirectDevice__com__set_Completed(handler)
        self._OnCompletedFn = fn
    

IID_IWiFiDirectDevice = comtypes.GUID('{72DEAAA8-72EB-4DAE-8A28-8513355D2777}')
class IWiFiDirectDevice(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectDevice)]
    [uuid(72DEAAA8-72EB-4DAE-8A28-8513355D2777)]
    interface IWiFiDirectDevice : IInspectable
    {
    [propget] HRESULT ConnectionStatus([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectConnectionStatus* value);
    [propget] HRESULT DeviceId([out] [retval] HSTRING* value);
    [eventadd] HRESULT ConnectionStatusChanged([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*, IInspectable*>* handler, [out] [retval] EventRegistrationToken* token);
    [eventremove] HRESULT ConnectionStatusChanged([in] EventRegistrationToken token);
    HRESULT GetConnectionEndpointPairs([out] [retval] Windows.Foundation.Collections.IVectorView<Windows.Networking.EndpointPair*>** value);
    }
    """
    _iid_ = IID_IWiFiDirectDevice
    def __init__(self):
        self._OnConnectionStatusChangedFn = None
        self._OnConnectionStatusChangedToken = None
        self._OnConnectionStatusChangedHandler = None
        self._OnConnectionStatusChangedHandlerClass = None
    
    @property
    def OnConnectionStatusChanged(self):
        logger.info("")
        # type:()->FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherConnectionStatusChangedEventArgs
        return self._OnConnectionStatusChangedFn
    
    @OnConnectionStatusChanged.setter
    def OnConnectionStatusChanged(self, fn):
        logger.info("")
        # type:(FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherConnectionStatusChangedEventArgs) -> None
        if (self._OnConnectionStatusChangedToken is not None):
            self._IWiFiDirectDevice__com_remove_ConnectionStatusChanged(self._OnConnectionStatusChangedToken)
            self._OnConnectionStatusChangedToken = None
            self._OnConnectionStatusChangedHandler = None
            self._OnConnectionStatusChangedHandlerClass = None
    
        if (fn is not None):
            self._OnConnectionStatusChangedHandlerClass = make_typed_event_handler_class(
                TypedEventHandler_2_WiFiDirectDevice_IInspectable,
                wintypes.POINTER(WiFiDirectDevice),
                wintypes.POINTER(IInspectable),
                fn
            )
            self._OnConnectionStatusChangedHandler = self._OnConnectionStatusChangedHandlerClass()
    
            self._OnConnectionStatusChangedToken = EventRegistrationToken()
            handler = self._OnConnectionStatusChangedHandler.QueryInterface(self._OnConnectionStatusChangedHandlerClass._event_handler_interface_)
            self._IWiFiDirectDevice__com_add_ConnectionStatusChanged(
                handler,
                ctypes.byref(self._OnConnectionStatusChangedToken)
            )
        self._OnConnectionStatusChangedFn = fn
    

IID_TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs = comtypes.GUID('{d04b0403-1fe2-532f-8e47-4823a14e624f}')
class TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs(comtypes.IUnknown):
    """
    [uuid(d04b0403-1fe2-532f-8e47-4823a14e624f)]
    interface TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs : IUnknown
    {
    HRESULT Invoke([in] WiFiDirectConnectionListener *sender, [in] WiFiDirectConnectionRequestedEventArgs *args);
    }
    """
    _iid_ = IID_TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs

IID_IWiFiDirectInformationElement = comtypes.GUID('{AFFB72D6-76BB-497E-AC8B-DC72838BC309}')
class IWiFiDirectInformationElement(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectInformationElement)]
    [uuid(AFFB72D6-76BB-497E-AC8B-DC72838BC309)]
    interface IWiFiDirectInformationElement : IInspectable
    {
    [propget] HRESULT Oui([out] [retval] Windows.Storage.Streams.IBuffer** value);
    [propput] HRESULT Oui([in] Windows.Storage.Streams.IBuffer* value);
    [propget] HRESULT OuiType([out] [retval] BYTE* value);
    [propput] HRESULT OuiType([in] BYTE value);
    [propget] HRESULT Value([out] [retval] Windows.Storage.Streams.IBuffer** value);
    [propput] HRESULT Value([in] Windows.Storage.Streams.IBuffer* value);
    }
    """
    _iid_ = IID_IWiFiDirectInformationElement

IID_TypedEventHandler_2_WiFiDirectDevice_IInspectable = comtypes.GUID('{9208929a-2a3c-50ad-aa08-a0a986edbabe}')
class TypedEventHandler_2_WiFiDirectDevice_IInspectable(comtypes.IUnknown):
    """
    [uuid(9208929a-2a3c-50ad-aa08-a0a986edbabe)]
    interface TypedEventHandler_2_WiFiDirectDevice_IInspectable : IUnknown
    {
    HRESULT Invoke([in] WiFiDirectDevice *sender, [in] IInspectable *args);
    }
    """
    _iid_ = IID_TypedEventHandler_2_WiFiDirectDevice_IInspectable

IID_IWiFiDirectConnectionParametersStatics = comtypes.GUID('{598AF493-7642-456F-B9D8-E8A9EB1F401A}')
class IWiFiDirectConnectionParametersStatics(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters)]
    [uuid(598AF493-7642-456F-B9D8-E8A9EB1F401A)]
    interface IWiFiDirectConnectionParametersStatics : IInspectable
    {
    HRESULT GetDevicePairingKinds([in] Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod configurationMethod, [out] [retval] Windows.Devices.Enumeration.DevicePairingKinds* result);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionParametersStatics

IID_IAsyncOperation_1_DeviceThumbnail = comtypes.GUID('{9FC2B0BB-E446-44E2-AA61-9CAB8F636AF2}')
class IAsyncOperation_1_DeviceThumbnail(IInspectable):
    """
    [uuid(2680336571, 58438, 17634, 170, 97, 156, 171, 143, 99, 106, 242)]
    interface IAsyncOperation_1_DeviceThumbnail : IInspectable
    {
    }
    """
    _iid_ = IID_IAsyncOperation_1_DeviceThumbnail

IID_IWiFiDirectConnectionParameters = comtypes.GUID('{B2E55405-5702-4B16-A02C-BBCD21EF6098}')
class IWiFiDirectConnectionParameters(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters)]
    [uuid(B2E55405-5702-4B16-A02C-BBCD21EF6098)]
    interface IWiFiDirectConnectionParameters : IInspectable
    {
    [propget] HRESULT GroupOwnerIntent([out] [retval] INT16* value);
    [propput] HRESULT GroupOwnerIntent([in] INT16 value);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionParameters

IID_IWiFiDirectConnectionParameters2 = comtypes.GUID('{AB3B0FBE-AA82-44B4-88C8-E3056B89801D}')
class IWiFiDirectConnectionParameters2(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters)]
    [uuid(AB3B0FBE-AA82-44B4-88C8-E3056B89801D)]
    interface IWiFiDirectConnectionParameters2 : IInspectable
    {
    [propget] HRESULT PreferenceOrderedConfigurationMethods([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod>** value);
    [propget] HRESULT PreferredPairingProcedure([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectPairingProcedure* value);
    [propput] HRESULT PreferredPairingProcedure([in] Windows.Devices.WiFiDirect.WiFiDirectPairingProcedure value);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionParameters2

IID_IAsyncOperationCompletedHandler_1_WiFiDirectDevice = comtypes.GUID('{d34abe17-fb19-57be-bc41-0eb83dea151c}')
class IAsyncOperationCompletedHandler_1_WiFiDirectDevice(comtypes.IUnknown):
    """
    [uuid(d34abe17-fb19-57be-bc41-0eb83dea151c)]
    interface IAsyncOperationCompletedHandler_1_WiFiDirectDevice : IUnknown
    {
    HRESULT Invoke([in] IAsyncOperation_1_WiFiDirectDevice *asyncInfo, [in] AsyncStatus status);
    }
    """
    _iid_ = IID_IAsyncOperationCompletedHandler_1_WiFiDirectDevice

IID_IDeviceInformation = comtypes.GUID('{ABA0FB95-4398-489D-8E44-E6130927011F}')
class IDeviceInformation(IInspectable):
    """
    [exclusiveto(Windows.Devices.Enumeration.DeviceInformation)]
    [uuid(ABA0FB95-4398-489D-8E44-E6130927011F)]
    interface IDeviceInformation : IInspectable
    {
    [propget] HRESULT Id([out] [retval] HSTRING* value);
    [propget] HRESULT Name([out] [retval] HSTRING* value);
    [propget] HRESULT IsEnabled([out] [retval] boolean* value);
    [propget] HRESULT IsDefault([out] [retval] boolean* value);
    [propget] HRESULT EnclosureLocation([out] [retval] Windows.Devices.Enumeration.EnclosureLocation** value);
    [propget] HRESULT Properties([out] [retval] Windows.Foundation.Collections.IMapView<HSTRING, IInspectable*>** value);
    HRESULT Update([in] Windows.Devices.Enumeration.DeviceInformationUpdate* updateInfo);
    HRESULT GetThumbnailAsync([out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.Enumeration.DeviceThumbnail*>** asyncOp);
    HRESULT GetGlyphThumbnailAsync([out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.Enumeration.DeviceThumbnail*>** asyncOp);
    }
    """
    _iid_ = IID_IDeviceInformation

IID_IWiFiDirectConnectionListener = comtypes.GUID('{699C1B0D-8D13-4EE9-B9EC-9C72F8251F7D}')
class IWiFiDirectConnectionListener(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionListener)]
    [uuid(699C1B0D-8D13-4EE9-B9EC-9C72F8251F7D)]
    interface IWiFiDirectConnectionListener : IInspectable
    {
    [eventadd] HRESULT ConnectionRequested([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectConnectionListener*, Windows.Devices.WiFiDirect.WiFiDirectConnectionRequestedEventArgs*>* handler, [out] [retval] EventRegistrationToken* token);
    [eventremove] HRESULT ConnectionRequested([in] EventRegistrationToken token);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionListener
    def __init__(self):
        self._OnConnectionRequestedFn = None
        self._OnConnectionRequestedToken = None
        self._OnConnectionRequestedHandler = None
        self._OnConnectionRequestedHandlerClass = None
    
    @property
    def OnConnectionRequested(self):
        logger.info("")
        # type:()->FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherConnectionRequestedEventArgs
        return self._OnConnectionRequestedFn
    
    @OnConnectionRequested.setter
    def OnConnectionRequested(self, fn):
        logger.info("")
        # type:(FWiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherConnectionRequestedEventArgs) -> None
        if (self._OnConnectionRequestedToken is not None):
            self._IWiFiDirectConnectionListener__com_remove_ConnectionRequested(self._OnConnectionRequestedToken)
            self._OnConnectionRequestedToken = None
            self._OnConnectionRequestedHandler = None
            self._OnConnectionRequestedHandlerClass = None
    
        if (fn is not None):
            self._OnConnectionRequestedHandlerClass = make_typed_event_handler_class(
                TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs,
                wintypes.POINTER(WiFiDirectConnectionListener),
                wintypes.POINTER(WiFiDirectConnectionRequestedEventArgs),
                fn
            )
            self._OnConnectionRequestedHandler = self._OnConnectionRequestedHandlerClass()
    
            self._OnConnectionRequestedToken = EventRegistrationToken()
            handler = self._OnConnectionRequestedHandler.QueryInterface(self._OnConnectionRequestedHandlerClass._event_handler_interface_)
            self._IWiFiDirectConnectionListener__com_add_ConnectionRequested(
                handler,
                ctypes.byref(self._OnConnectionRequestedToken)
            )
        self._OnConnectionRequestedFn = fn
    

IID_IWiFiDirectConnectionRequestedEventArgs = comtypes.GUID('{F99D20BE-D38D-484F-8215-E7B65ABF244C}')
class IWiFiDirectConnectionRequestedEventArgs(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectConnectionRequestedEventArgs)]
    [uuid(F99D20BE-D38D-484F-8215-E7B65ABF244C)]
    interface IWiFiDirectConnectionRequestedEventArgs : IInspectable
    {
    HRESULT GetConnectionRequest([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectConnectionRequest** result);
    }
    """
    _iid_ = IID_IWiFiDirectConnectionRequestedEventArgs

IID_IWiFiDirectAdvertisementPublisherStatusChangedEventArgs = comtypes.GUID('{AAFDE53C-5481-46E6-90DD-32116518F192}')
class IWiFiDirectAdvertisementPublisherStatusChangedEventArgs(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatusChangedEventArgs)]
    [uuid(AAFDE53C-5481-46E6-90DD-32116518F192)]
    interface IWiFiDirectAdvertisementPublisherStatusChangedEventArgs : IInspectable
    {
    [propget] HRESULT Status([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatus* value);
    [propget] HRESULT Error([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectError* value);
    }
    """
    _iid_ = IID_IWiFiDirectAdvertisementPublisherStatusChangedEventArgs

IID_IMapView_2_HSTRING_IInspectable = comtypes.GUID('{e480ce40-a338-4ada-adcf-272272e48cb9}')
class IMapView_2_HSTRING_IInspectable(IInspectable):
    """
    uuid(e480ce40-a338-4ada-adcf-272272e48cb9)
    interface IMapView_2_HSTRING_IInspectable : IInspectable
    {
    }
    """
    _iid_ = IID_IMapView_2_HSTRING_IInspectable

IID_IWiFiDirectDeviceStatics = comtypes.GUID('{E86CB57C-3AAC-4851-A792-482AAF931B04}')
class IWiFiDirectDeviceStatics(IInspectable):
    """
    [exclusiveto(Windows.Devices.WiFiDirect.WiFiDirectDevice)]
    [uuid(E86CB57C-3AAC-4851-A792-482AAF931B04)]
    interface IWiFiDirectDeviceStatics : IInspectable
    {
    [overload("GetDeviceSelector")] HRESULT GetDeviceSelector([out] [retval] HSTRING* deviceSelector);
    [overload("FromIdAsync")] HRESULT FromIdAsync([in] HSTRING deviceId, [out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** asyncOp);
    }
    """
    _iid_ = IID_IWiFiDirectDeviceStatics

IID_IVector_1_WiFiDirectInformationElement = comtypes.GUID('{913337e9-11a1-4345-a3a2-4e7f956e222d}')
class IVector_1_WiFiDirectInformationElement(IInspectable):
    """
    uuid(913337e9-11a1-4345-a3a2-4e7f956e222d)
    interface IVector_1_WiFiDirectInformationElement : IInspectable
    {
    }
    """
    _iid_ = IID_IVector_1_WiFiDirectInformationElement

IID_IVectorView_1_EndpointPair = comtypes.GUID('{bbe1fa4c-b0e3-4583-baef-1f1b2e483e56}')
class IVectorView_1_EndpointPair(IInspectable):
    """
    uuid(bbe1fa4c-b0e3-4583-baef-1f1b2e483e56)
    interface IVectorView_1_EndpointPair : IInspectable
    {
    }
    """
    _iid_ = IID_IVectorView_1_EndpointPair

IID_IPasswordCredential = comtypes.GUID('{6AB18989-C720-41A7-A6C1-FEADB36329A0}')
class IPasswordCredential(IInspectable):
    """
    [exclusiveto(Windows.Security.Credentials.PasswordCredential)]
    [uuid(6AB18989-C720-41A7-A6C1-FEADB36329A0)]
    interface IPasswordCredential : IInspectable
    {
    [propget] HRESULT Resource([out] [retval] HSTRING* resource);
    [propput] HRESULT Resource([in] HSTRING resource);
    [propget] HRESULT UserName([out] [retval] HSTRING* userName);
    [propput] HRESULT UserName([in] HSTRING userName);
    [propget] HRESULT Password([out] [retval] HSTRING* password);
    [propput] HRESULT Password([in] HSTRING password);
    HRESULT RetrievePassword();
    [propget] HRESULT Properties([out] [retval] Windows.Foundation.Collections.IPropertySet** props);
    }
    """
    _iid_ = IID_IPasswordCredential

IID_TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs = comtypes.GUID('{de73cba7-370d-550c-b23a-53dd0b4e480d}')
class TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs(comtypes.IUnknown):
    """
    [uuid(de73cba7-370d-550c-b23a-53dd0b4e480d)]
    interface TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs : IUnknown
    {
    HRESULT Invoke([in] WiFiDirectAdvertisementPublisher *sender, [in] WiFiDirectAdvertisementPublisherStatusChangedEventArgs *args);
    }
    """
    _iid_ = IID_TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs

class WiFiDirectDevice(IWiFiDirectDevice):
    """
    [static(Windows.Devices.WiFiDirect.IWiFiDirectDeviceStatics, Windows.Foundation.UniversalApiContract, 1.0)]
    [static(Windows.Devices.WiFiDirect.IWiFiDirectDeviceStatics2, Windows.Foundation.UniversalApiContract, 1.0)]
    runtimeclass WiFiDirectDevice
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectDevice;
    }
    """

class IWiFiDirectDeviceStatics_s(IInspectable):
    _iid_ = IID_IWiFiDirectDeviceStatics
    def __new__(cls):
        static = activate_static("Windows.Devices.WiFiDirect.WiFiDirectDevice", IWiFiDirectDeviceStatics)
        return static
    
class IWiFiDirectDeviceStatics2_s(IInspectable):
    _iid_ = IID_IWiFiDirectDeviceStatics2
    def __new__(cls):
        static = activate_static("Windows.Devices.WiFiDirect.WiFiDirectDevice", IWiFiDirectDeviceStatics2)
        return static
    
class WiFiDirectConnectionRequest(IWiFiDirectConnectionRequest):
    """
    runtimeclass WiFiDirectConnectionRequest
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectConnectionRequest;
    }
    """

class WiFiDirectInformationElement(IWiFiDirectInformationElement):
    """
    [activatable(Windows.Foundation.UniversalApiContract, 1.0)]
    [static(Windows.Devices.WiFiDirect.IWiFiDirectInformationElementStatics, Windows.Foundation.UniversalApiContract, 1.0)]
    runtimeclass WiFiDirectInformationElement
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectInformationElement;
    }
    """
    def __new__(cls):
        instance = activate_instance('Windows.Devices.WiFiDirect.WiFiDirectInformationElement', IWiFiDirectInformationElement)
        # XXX This calls __init__ to wrap the object just created so the
        #     pythonic methods in the wrapper can be used (eg event
        #     hooking), do it in activate_instance or find another
        #     mechanism?
        instance.__init__()
        return instance
    

class IWiFiDirectInformationElementStatics_s(IInspectable):
    _iid_ = IID_IWiFiDirectInformationElementStatics
    def __new__(cls):
        static = activate_static("Windows.Devices.WiFiDirect.WiFiDirectInformationElement", IWiFiDirectInformationElementStatics)
        return static
    
class WiFiDirectConnectionParameters(IWiFiDirectConnectionParameters):
    """
    [activatable(Windows.Foundation.UniversalApiContract, 1.0)]
    [static(Windows.Devices.WiFiDirect.IWiFiDirectConnectionParametersStatics, Windows.Foundation.UniversalApiContract, 2.0)]
    runtimeclass WiFiDirectConnectionParameters
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectConnectionParameters;
    }
    """
    def __new__(cls):
        instance = activate_instance('Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters', IWiFiDirectConnectionParameters)
        # XXX This calls __init__ to wrap the object just created so the
        #     pythonic methods in the wrapper can be used (eg event
        #     hooking), do it in activate_instance or find another
        #     mechanism?
        instance.__init__()
        return instance
    

class IWiFiDirectConnectionParametersStatics_s(IInspectable):
    _iid_ = IID_IWiFiDirectConnectionParametersStatics
    def __new__(cls):
        static = activate_static("Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters", IWiFiDirectConnectionParametersStatics)
        return static
    
class WiFiDirectConnectionRequestedEventArgs(IWiFiDirectConnectionRequestedEventArgs):
    """
    runtimeclass WiFiDirectConnectionRequestedEventArgs
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectConnectionRequestedEventArgs;
    }
    """

class WiFiDirectConnectionListener(IWiFiDirectConnectionListener):
    """
    [activatable(Windows.Foundation.UniversalApiContract, 1.0)]
    runtimeclass WiFiDirectConnectionListener
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectConnectionListener;
    }
    """
    def __new__(cls):
        instance = activate_instance('Windows.Devices.WiFiDirect.WiFiDirectConnectionListener', IWiFiDirectConnectionListener)
        # XXX This calls __init__ to wrap the object just created so the
        #     pythonic methods in the wrapper can be used (eg event
        #     hooking), do it in activate_instance or find another
        #     mechanism?
        instance.__init__()
        return instance
    

class PasswordCredential(IPasswordCredential):
    """
    runtimeclass PasswordCredential
    {
    [default] interface Windows.Security.Credentials.IPasswordCredential;
    }
    """

class WiFiDirectAdvertisementPublisherStatusChangedEventArgs(IWiFiDirectAdvertisementPublisherStatusChangedEventArgs):
    """
    runtimeclass WiFiDirectAdvertisementPublisherStatusChangedEventArgs
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectAdvertisementPublisherStatusChangedEventArgs;
    }
    """

class WiFiDirectAdvertisementPublisher(IWiFiDirectAdvertisementPublisher):
    """
    [activatable(Windows.Foundation.UniversalApiContract, 1.0)]
    runtimeclass WiFiDirectAdvertisementPublisher
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectAdvertisementPublisher;
    }
    """
    def __new__(cls):
        instance = activate_instance('Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisher', IWiFiDirectAdvertisementPublisher)
        # XXX This calls __init__ to wrap the object just created so the
        #     pythonic methods in the wrapper can be used (eg event
        #     hooking), do it in activate_instance or find another
        #     mechanism?
        instance.__init__()
        return instance
    

class DeviceInformation(IDeviceInformation):
    """
    runtimeclass DeviceInformation
    {
    [default] interface Windows.Devices.Enumeration.IDeviceInformation;
    }
    """

class WiFiDirectLegacySettings(IWiFiDirectLegacySettings):
    """
    runtimeclass WiFiDirectLegacySettings
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectLegacySettings;
    }
    """

class WiFiDirectAdvertisement(IWiFiDirectAdvertisement):
    """
    runtimeclass WiFiDirectAdvertisement
    {
    [default] interface Windows.Devices.WiFiDirect.IWiFiDirectAdvertisement;
    }
    """

EnclosureLocation._methods_ = [
]

IWiFiDirectDeviceStatics2._methods_ = [
    # [overload("GetDeviceSelector")] HRESULT GetDeviceSelector([in] Windows.Devices.WiFiDirect.WiFiDirectDeviceSelectorType type,[out] [retval] HSTRING* result)
    comtypes.COMMETHOD(
        ['overload("GetDeviceSelector")'], wintypes.HRESULT, 'GetDeviceSelector',
        (['in'], WiFiDirectDeviceSelectorType, 'type'),
        (['out','retval'], wintypes.POINTER(HSTRING), 'result'),
    ),
    # [overload("FromIdAsync")] HRESULT FromIdAsync([in] HSTRING deviceId,[in] Windows.Devices.WiFiDirect.WiFiDirectConnectionParameters* connectionParameters,[out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** result)
    comtypes.COMMETHOD(
        ['overload("FromIdAsync")'], wintypes.HRESULT, 'FromIdAsync',
        (['in'], HSTRING, 'deviceId'),
        (['in'], wintypes.POINTER(WiFiDirectConnectionParameters), 'connectionParameters'),
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IAsyncOperation_1_WiFiDirectDevice)), 'result'),
    ),
]

IWiFiDirectAdvertisement._methods_ = [
    # [propget] HRESULT InformationElements([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'InformationElements',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectInformationElement)), 'value'),
    ),
    # [propput] HRESULT InformationElements([in] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>* value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'InformationElements',
        (['in'], wintypes.POINTER(IVector_1_WiFiDirectInformationElement), 'value'),
    ),
    # [propget] HRESULT ListenStateDiscoverability([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementListenStateDiscoverability* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'ListenStateDiscoverability',
        (['out','retval'], wintypes.POINTER(WiFiDirectAdvertisementListenStateDiscoverability), 'value'),
    ),
    # [propput] HRESULT ListenStateDiscoverability([in] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementListenStateDiscoverability value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'ListenStateDiscoverability',
        (['in'], WiFiDirectAdvertisementListenStateDiscoverability, 'value'),
    ),
    # [propget] HRESULT IsAutonomousGroupOwnerEnabled([out] [retval] boolean* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'IsAutonomousGroupOwnerEnabled',
        (['out','retval'], wintypes.POINTER(wintypes.BOOL), 'value'),
    ),
    # [propput] HRESULT IsAutonomousGroupOwnerEnabled([in] boolean value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'IsAutonomousGroupOwnerEnabled',
        (['in'], wintypes.BOOL, 'value'),
    ),
    # [propget] HRESULT LegacySettings([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectLegacySettings** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'LegacySettings',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(WiFiDirectLegacySettings)), 'value'),
    ),
]

IWiFiDirectAdvertisementPublisher._methods_ = [
    # [propget] HRESULT Advertisement([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisement** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Advertisement',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(WiFiDirectAdvertisement)), 'value'),
    ),
    # [propget] HRESULT Status([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatus* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Status',
        (['out','retval'], wintypes.POINTER(WiFiDirectAdvertisementPublisherStatus), 'value'),
    ),
    # [eventadd] HRESULT StatusChanged([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisher*,Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatusChangedEventArgs*>* handler,[out] [retval] EventRegistrationToken* token)
    comtypes.COMMETHOD(
        ['eventadd'], wintypes.HRESULT, 'add_StatusChanged',
        (['in'], wintypes.POINTER(TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs), 'handler'),
        (['out','retval'], wintypes.POINTER(EventRegistrationToken), 'token'),
    ),
    # [eventremove] HRESULT StatusChanged([in] EventRegistrationToken token)
    comtypes.COMMETHOD(
        ['eventremove'], wintypes.HRESULT, 'remove_StatusChanged',
        (['in'], EventRegistrationToken, 'token'),
    ),
    # [None] HRESULT Start()
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Start',
    ),
    # [None] HRESULT Stop()
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Stop',
    ),
]

IWiFiDirectInformationElementStatics._methods_ = [
    # [None] HRESULT CreateFromBuffer([in] Windows.Storage.Streams.IBuffer* buffer,[out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** result)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'CreateFromBuffer',
        (['in'], wintypes.POINTER(IBuffer), 'buffer'),
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectInformationElement)), 'result'),
    ),
    # [None] HRESULT CreateFromDeviceInformation([in] Windows.Devices.Enumeration.DeviceInformation* deviceInformation,[out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectInformationElement*>** result)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'CreateFromDeviceInformation',
        (['in'], wintypes.POINTER(DeviceInformation), 'deviceInformation'),
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectInformationElement)), 'result'),
    ),
]

IWiFiDirectAdvertisement2._methods_ = [
    # [propget] HRESULT SupportedConfigurationMethods([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod>** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'SupportedConfigurationMethods',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectConfigurationMethod)), 'value'),
    ),
]

IWiFiDirectConnectionRequest._methods_ = [
    # [propget] HRESULT DeviceInformation([out] [retval] Windows.Devices.Enumeration.DeviceInformation** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'DeviceInformation',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(DeviceInformation)), 'value'),
    ),
]

IVector_1_WiFiDirectConfigurationMethod._methods_ = [
]

IWiFiDirectLegacySettings._methods_ = [
    # [propget] HRESULT IsEnabled([out] [retval] boolean* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'IsEnabled',
        (['out','retval'], wintypes.POINTER(wintypes.BOOL), 'value'),
    ),
    # [propput] HRESULT IsEnabled([in] boolean value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'IsEnabled',
        (['in'], wintypes.BOOL, 'value'),
    ),
    # [propget] HRESULT Ssid([out] [retval] HSTRING* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Ssid',
        (['out','retval'], wintypes.POINTER(HSTRING), 'value'),
    ),
    # [propput] HRESULT Ssid([in] HSTRING value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Ssid',
        (['in'], HSTRING, 'value'),
    ),
    # [propget] HRESULT Passphrase([out] [retval] Windows.Security.Credentials.PasswordCredential** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Passphrase',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(PasswordCredential)), 'value'),
    ),
    # [propput] HRESULT Passphrase([in] Windows.Security.Credentials.PasswordCredential* value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Passphrase',
        (['in'], wintypes.POINTER(PasswordCredential), 'value'),
    ),
]

DeviceInformationUpdate._methods_ = [
]

IPropertySet._methods_ = [
]

IBuffer._methods_ = [
    # [propget] HRESULT Capacity([out] [retval] UINT32* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Capacity',
        (['out','retval'], wintypes.POINTER(wintypes.ULONG), 'value'),
    ),
    # [propget] HRESULT Length([out] [retval] UINT32* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Length',
        (['out','retval'], wintypes.POINTER(wintypes.ULONG), 'value'),
    ),
    # [propput] HRESULT Length([in] UINT32 value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Length',
        (['in'], wintypes.ULONG, 'value'),
    ),
]

IAsyncOperation_1_WiFiDirectDevice._methods_ = [
    # [propput] HRESULT Completed([in] IAsyncOperationCompletedHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*>* handler)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Completed',
        (['in'], wintypes.POINTER(IAsyncOperationCompletedHandler_1_WiFiDirectDevice), 'handler'),
    ),
    # [propget] HRESULT Completed([out] [retval] IAsyncOperationCompletedHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** handler)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Completed',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IAsyncOperationCompletedHandler_1_WiFiDirectDevice)), 'handler'),
    ),
    # [None] HRESULT GetResults([out] [retval] Windows.Devices.WiFiDirect.IWiFiDirectDevice** results)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetResults',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IWiFiDirectDevice)), 'results'),
    ),
]

IWiFiDirectDevice._methods_ = [
    # [propget] HRESULT ConnectionStatus([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectConnectionStatus* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'ConnectionStatus',
        (['out','retval'], wintypes.POINTER(WiFiDirectConnectionStatus), 'value'),
    ),
    # [propget] HRESULT DeviceId([out] [retval] HSTRING* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'DeviceId',
        (['out','retval'], wintypes.POINTER(HSTRING), 'value'),
    ),
    # [eventadd] HRESULT ConnectionStatusChanged([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectDevice*,IInspectable*>* handler,[out] [retval] EventRegistrationToken* token)
    comtypes.COMMETHOD(
        ['eventadd'], wintypes.HRESULT, 'add_ConnectionStatusChanged',
        (['in'], wintypes.POINTER(TypedEventHandler_2_WiFiDirectDevice_IInspectable), 'handler'),
        (['out','retval'], wintypes.POINTER(EventRegistrationToken), 'token'),
    ),
    # [eventremove] HRESULT ConnectionStatusChanged([in] EventRegistrationToken token)
    comtypes.COMMETHOD(
        ['eventremove'], wintypes.HRESULT, 'remove_ConnectionStatusChanged',
        (['in'], EventRegistrationToken, 'token'),
    ),
    # [None] HRESULT GetConnectionEndpointPairs([out] [retval] Windows.Foundation.Collections.IVectorView<Windows.Networking.EndpointPair*>** value)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetConnectionEndpointPairs',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVectorView_1_EndpointPair)), 'value'),
    ),
]

TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs._methods_ = [
    # [None] HRESULT Invoke([in] WiFiDirectConnectionListener* sender,[in] WiFiDirectConnectionRequestedEventArgs* args)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Invoke',
        (['in'], wintypes.POINTER(WiFiDirectConnectionListener), 'sender'),
        (['in'], wintypes.POINTER(WiFiDirectConnectionRequestedEventArgs), 'args'),
    ),
]

IWiFiDirectInformationElement._methods_ = [
    # [propget] HRESULT Oui([out] [retval] Windows.Storage.Streams.IBuffer** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Oui',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IBuffer)), 'value'),
    ),
    # [propput] HRESULT Oui([in] Windows.Storage.Streams.IBuffer* value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Oui',
        (['in'], wintypes.POINTER(IBuffer), 'value'),
    ),
    # [propget] HRESULT OuiType([out] [retval] BYTE* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'OuiType',
        (['out','retval'], wintypes.POINTER(wintypes.BYTE), 'value'),
    ),
    # [propput] HRESULT OuiType([in] BYTE value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'OuiType',
        (['in'], wintypes.BYTE, 'value'),
    ),
    # [propget] HRESULT Value([out] [retval] Windows.Storage.Streams.IBuffer** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Value',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IBuffer)), 'value'),
    ),
    # [propput] HRESULT Value([in] Windows.Storage.Streams.IBuffer* value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Value',
        (['in'], wintypes.POINTER(IBuffer), 'value'),
    ),
]

TypedEventHandler_2_WiFiDirectDevice_IInspectable._methods_ = [
    # [None] HRESULT Invoke([in] WiFiDirectDevice* sender,[in] IInspectable* args)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Invoke',
        (['in'], wintypes.POINTER(WiFiDirectDevice), 'sender'),
        (['in'], wintypes.POINTER(IInspectable), 'args'),
    ),
]

IWiFiDirectConnectionParametersStatics._methods_ = [
    # [None] HRESULT GetDevicePairingKinds([in] Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod configurationMethod,[out] [retval] Windows.Devices.Enumeration.DevicePairingKinds* result)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetDevicePairingKinds',
        (['in'], WiFiDirectConfigurationMethod, 'configurationMethod'),
        (['out','retval'], wintypes.POINTER(DevicePairingKinds), 'result'),
    ),
]

IAsyncOperation_1_DeviceThumbnail._methods_ = [
]

IWiFiDirectConnectionParameters._methods_ = [
    # [propget] HRESULT GroupOwnerIntent([out] [retval] INT16* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'GroupOwnerIntent',
        (['out','retval'], wintypes.POINTER(wintypes.SHORT), 'value'),
    ),
    # [propput] HRESULT GroupOwnerIntent([in] INT16 value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'GroupOwnerIntent',
        (['in'], wintypes.SHORT, 'value'),
    ),
]

IWiFiDirectConnectionParameters2._methods_ = [
    # [propget] HRESULT PreferenceOrderedConfigurationMethods([out] [retval] Windows.Foundation.Collections.IVector<Windows.Devices.WiFiDirect.WiFiDirectConfigurationMethod>** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'PreferenceOrderedConfigurationMethods',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IVector_1_WiFiDirectConfigurationMethod)), 'value'),
    ),
    # [propget] HRESULT PreferredPairingProcedure([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectPairingProcedure* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'PreferredPairingProcedure',
        (['out','retval'], wintypes.POINTER(WiFiDirectPairingProcedure), 'value'),
    ),
    # [propput] HRESULT PreferredPairingProcedure([in] Windows.Devices.WiFiDirect.WiFiDirectPairingProcedure value)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'PreferredPairingProcedure',
        (['in'], WiFiDirectPairingProcedure, 'value'),
    ),
]

IAsyncOperationCompletedHandler_1_WiFiDirectDevice._methods_ = [
    # [None] HRESULT Invoke([in] IAsyncOperation_1_WiFiDirectDevice* asyncInfo,[in] AsyncStatus status)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Invoke',
        (['in'], wintypes.POINTER(IAsyncOperation_1_WiFiDirectDevice), 'asyncInfo'),
        (['in'], AsyncStatus, 'status'),
    ),
]

IDeviceInformation._methods_ = [
    # [propget] HRESULT Id([out] [retval] HSTRING* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Id',
        (['out','retval'], wintypes.POINTER(HSTRING), 'value'),
    ),
    # [propget] HRESULT Name([out] [retval] HSTRING* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Name',
        (['out','retval'], wintypes.POINTER(HSTRING), 'value'),
    ),
    # [propget] HRESULT IsEnabled([out] [retval] boolean* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'IsEnabled',
        (['out','retval'], wintypes.POINTER(wintypes.BOOL), 'value'),
    ),
    # [propget] HRESULT IsDefault([out] [retval] boolean* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'IsDefault',
        (['out','retval'], wintypes.POINTER(wintypes.BOOL), 'value'),
    ),
    # [propget] HRESULT EnclosureLocation([out] [retval] Windows.Devices.Enumeration.EnclosureLocation** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'EnclosureLocation',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(EnclosureLocation)), 'value'),
    ),
    # [propget] HRESULT Properties([out] [retval] Windows.Foundation.Collections.IMapView<HSTRING,IInspectable*>** value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Properties',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IMapView_2_HSTRING_IInspectable)), 'value'),
    ),
    # [None] HRESULT Update([in] Windows.Devices.Enumeration.DeviceInformationUpdate* updateInfo)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Update',
        (['in'], wintypes.POINTER(DeviceInformationUpdate), 'updateInfo'),
    ),
    # [None] HRESULT GetThumbnailAsync([out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.Enumeration.DeviceThumbnail*>** asyncOp)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetThumbnailAsync',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IAsyncOperation_1_DeviceThumbnail)), 'asyncOp'),
    ),
    # [None] HRESULT GetGlyphThumbnailAsync([out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.Enumeration.DeviceThumbnail*>** asyncOp)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetGlyphThumbnailAsync',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IAsyncOperation_1_DeviceThumbnail)), 'asyncOp'),
    ),
]

IWiFiDirectConnectionListener._methods_ = [
    # [eventadd] HRESULT ConnectionRequested([in] Windows.Foundation.TypedEventHandler<Windows.Devices.WiFiDirect.WiFiDirectConnectionListener*,Windows.Devices.WiFiDirect.WiFiDirectConnectionRequestedEventArgs*>* handler,[out] [retval] EventRegistrationToken* token)
    comtypes.COMMETHOD(
        ['eventadd'], wintypes.HRESULT, 'add_ConnectionRequested',
        (['in'], wintypes.POINTER(TypedEventHandler_2_WiFiDirectConnectionListener_WiFiDirectConnectionRequestedEventArgs), 'handler'),
        (['out','retval'], wintypes.POINTER(EventRegistrationToken), 'token'),
    ),
    # [eventremove] HRESULT ConnectionRequested([in] EventRegistrationToken token)
    comtypes.COMMETHOD(
        ['eventremove'], wintypes.HRESULT, 'remove_ConnectionRequested',
        (['in'], EventRegistrationToken, 'token'),
    ),
]

IWiFiDirectConnectionRequestedEventArgs._methods_ = [
    # [None] HRESULT GetConnectionRequest([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectConnectionRequest** result)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetConnectionRequest',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(WiFiDirectConnectionRequest)), 'result'),
    ),
]

IWiFiDirectAdvertisementPublisherStatusChangedEventArgs._methods_ = [
    # [propget] HRESULT Status([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectAdvertisementPublisherStatus* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Status',
        (['out','retval'], wintypes.POINTER(WiFiDirectAdvertisementPublisherStatus), 'value'),
    ),
    # [propget] HRESULT Error([out] [retval] Windows.Devices.WiFiDirect.WiFiDirectError* value)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Error',
        (['out','retval'], wintypes.POINTER(WiFiDirectError), 'value'),
    ),
]

IMapView_2_HSTRING_IInspectable._methods_ = [
]

IWiFiDirectDeviceStatics._methods_ = [
    # [overload("GetDeviceSelector")] HRESULT GetDeviceSelector([out] [retval] HSTRING* deviceSelector)
    comtypes.COMMETHOD(
        ['overload("GetDeviceSelector")'], wintypes.HRESULT, 'GetDeviceSelector',
        (['out','retval'], wintypes.POINTER(HSTRING), 'deviceSelector'),
    ),
    # [overload("FromIdAsync")] HRESULT FromIdAsync([in] HSTRING deviceId,[out] [retval] Windows.Foundation.IAsyncOperation<Windows.Devices.WiFiDirect.WiFiDirectDevice*>** asyncOp)
    comtypes.COMMETHOD(
        ['overload("FromIdAsync")'], wintypes.HRESULT, 'FromIdAsync',
        (['in'], HSTRING, 'deviceId'),
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IAsyncOperation_1_WiFiDirectDevice)), 'asyncOp'),
    ),
]

IVector_1_WiFiDirectInformationElement._methods_ = [
]

IVectorView_1_EndpointPair._methods_ = [
]

IPasswordCredential._methods_ = [
    # [propget] HRESULT Resource([out] [retval] HSTRING* resource)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Resource',
        (['out','retval'], wintypes.POINTER(HSTRING), 'resource'),
    ),
    # [propput] HRESULT Resource([in] HSTRING resource)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Resource',
        (['in'], HSTRING, 'resource'),
    ),
    # [propget] HRESULT UserName([out] [retval] HSTRING* userName)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'UserName',
        (['out','retval'], wintypes.POINTER(HSTRING), 'userName'),
    ),
    # [propput] HRESULT UserName([in] HSTRING userName)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'UserName',
        (['in'], HSTRING, 'userName'),
    ),
    # [propget] HRESULT Password([out] [retval] HSTRING* password)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Password',
        (['out','retval'], wintypes.POINTER(HSTRING), 'password'),
    ),
    # [propput] HRESULT Password([in] HSTRING password)
    comtypes.COMMETHOD(
        ['propput'], wintypes.HRESULT, 'Password',
        (['in'], HSTRING, 'password'),
    ),
    # [None] HRESULT RetrievePassword()
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'RetrievePassword',
    ),
    # [propget] HRESULT Properties([out] [retval] Windows.Foundation.Collections.IPropertySet** props)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Properties',
        (['out','retval'], wintypes.POINTER(wintypes.POINTER(IPropertySet)), 'props'),
    ),
]

TypedEventHandler_2_WiFiDirectAdvertisementPublisher_WiFiDirectAdvertisementPublisherStatusChangedEventArgs._methods_ = [
    # [None] HRESULT Invoke([in] WiFiDirectAdvertisementPublisher* sender,[in] WiFiDirectAdvertisementPublisherStatusChangedEventArgs* args)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Invoke',
        (['in'], wintypes.POINTER(WiFiDirectAdvertisementPublisher), 'sender'),
        (['in'], wintypes.POINTER(WiFiDirectAdvertisementPublisherStatusChangedEventArgs), 'args'),
    ),
]

