# Autogenerated from wrtbase.idl on 2023-09-13 12:54:59.689000
from ctypes import wintypes
import comtypes

HSTRING = wintypes.HANDLE
ENUM = wintypes.UINT

class TrustLevel(ENUM):
    """
    enum TrustLevel
    {
    BaseTrust    = 0,
    PartialTrust = 1,
    FullTrust    = 2
    };
    """
    BaseTrust = 0
    PartialTrust = 1
    FullTrust = 2
    
IID_IInspectable = comtypes.GUID('{AF86E2E0-B12D-4c6a-9C5A-D7AA65101E90}')
class IInspectable(comtypes.IUnknown):
    """
    uuid(AF86E2E0-B12D-4c6a-9C5A-D7AA65101E90),
    interface IInspectable : IUnknown
    {
    HRESULT GetIids([out] ULONG *iidCount, [out] IID **iids);
    HRESULT GetRuntimeClassName( [out] HSTRING *className);
    HRESULT GetTrustLevel([out] TrustLevel *trustLevel);
    }
    """
    _iid_ = IID_IInspectable

IInspectable._methods_ = [
    # [None] HRESULT GetIids([out] ULONG* iidCount,[out] IID** iids)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetIids',
        (['out'], wintypes.POINTER(wintypes.ULONG), 'iidCount'),
        (['out'], wintypes.POINTER(wintypes.POINTER(comtypes.IID)), 'iids'),
    ),
    # [None] HRESULT GetRuntimeClassName([out] HSTRING* className)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetRuntimeClassName',
        (['out'], wintypes.POINTER(HSTRING), 'className'),
    ),
    # [None] HRESULT GetTrustLevel([out] TrustLevel* trustLevel)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'GetTrustLevel',
        (['out'], wintypes.POINTER(TrustLevel), 'trustLevel'),
    ),
]

class AsyncStatus(ENUM):
    """
    enum AsyncStatus
    {
    Started = 0,
    Completed = 1,
    Canceled = 2,
    Error = 3
    };
    """
    Started = 0
    Completed = 1
    Canceled = 2
    Error = 3
    
IID_ITypedEventHandler = comtypes.GUID('{9DE1C534-6AE1-11E0-84E1-18A905BCC53F}')
class ITypedEventHandler(comtypes.IUnknown):
    """
    [uuid(2648818996, 27361, 4576, 132, 225, 24, 169, 5, 188, 197, 63)]
    interface ITypedEventHandler : IUnknown
    {
    HRESULT Invoke([in] IInspectable *sender, [in] IInspectable *args);
    }
    """
    _iid_ = IID_ITypedEventHandler

IID_IAsyncInfo = comtypes.GUID('{00000036-0000-0000-C000-000000000046}')
class IAsyncInfo(IInspectable):
    """
    uuid(00000036-0000-0000-C000-000000000046),
    interface IAsyncInfo : IInspectable
    {
    [propget] HRESULT Id([out, retval] UINT32 *id);
    [propget] HRESULT Status([out, retval] AsyncStatus *status);
    [propget] HRESULT ErrorCode([out,retval] HRESULT *errorCode);
    HRESULT Cancel();
    HRESULT Close();
    }
    """
    _iid_ = IID_IAsyncInfo

IID_IAgileObject = comtypes.GUID('{94EA2B94-E9CC-49E0-C0FF-EE64CA8F5B90}')
class IAgileObject(comtypes.IUnknown):
    """
    uuid(94EA2B94-E9CC-49E0-C0FF-EE64CA8F5B90),
    interface IAgileObject : IUnknown
    {
    }
    """
    _iid_ = IID_IAgileObject

IID_IAsyncOperation = comtypes.GUID('{9FC2B0BB-E446-44E2-AA61-9CAB8F636AF2}')
class IAsyncOperation(IAsyncInfo):
    """
    uuid(2680336571, 58438, 17634, 170, 97, 156, 171, 143, 99, 106, 242)
    interface IAsyncOperation : IAsyncInfo
    {
    }
    """
    _iid_ = IID_IAsyncOperation

ITypedEventHandler._methods_ = [
    # [None] HRESULT Invoke([in] IInspectable* sender,[in] IInspectable* args)
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Invoke',
        (['in'], wintypes.POINTER(IInspectable), 'sender'),
        (['in'], wintypes.POINTER(IInspectable), 'args'),
    ),
]

IAsyncInfo._methods_ = [
    # [propget] HRESULT Id([out] [ retval] UINT32* id)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Id',
        (['out',' retval'], wintypes.POINTER(wintypes.ULONG), 'id'),
    ),
    # [propget] HRESULT Status([out] [ retval] AsyncStatus* status)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'Status',
        (['out',' retval'], wintypes.POINTER(AsyncStatus), 'status'),
    ),
    # [propget] HRESULT ErrorCode([out] [retval] HRESULT* errorCode)
    comtypes.COMMETHOD(
        ['propget'], wintypes.HRESULT, 'ErrorCode',
        (['out','retval'], wintypes.POINTER(wintypes.HRESULT), 'errorCode'),
    ),
    # [None] HRESULT Cancel()
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Cancel',
    ),
    # [None] HRESULT Close()
    comtypes.COMMETHOD(
        [], wintypes.HRESULT, 'Close',
    ),
]

IAgileObject._methods_ = [
]

IAsyncOperation._methods_ = [
]

